### ISSUE TITLE
Vagrant 1.9.2 macOS installer package is unsigned

### ISSUE THREAD

**Issue by timsutton** [mitchellh/vagrant-installers#102]
Not sure if this is the right place to log this, but just thought I'd point out that the 1.9.2 installer pkg for macOS isn't signed as previous releases have been (1.9.1 on the left, 1.9.2 on the right):

<img width="1829" alt="screenshot 2017-02-28 17 08 40" src="https://cloud.githubusercontent.com/assets/119358/23436451/95bab446-fdd8-11e6-9e9b-0f98bcc72cf0.png">

**Comment by chrisroberts** [comment]
@timsutton Thanks for the report. I'm having a look now.

**Comment by chrisroberts** [comment]
Cleaned up the signing interactions in the packaging script for MacOS and the modifications have been pushed into `master`. Next release will have this issue properly fixed and will be out in the next couple days. Thanks for reporting this issue @timsutton!

**Comment by Erulezz** [comment]
Hi,

Any ETA on 1.9.2 ? :)
