### ISSUE TITLE
Uninstall Tool should delete the ~/.vagrant.d directory to delete the user data.

### ISSUE THREAD

**Issue by AnneTheAgile** [mitchellh/vagrant-installers#35]
Today I was fixing my Vagrant, which had the following error on every command except --version; 
```
# OK
$ Vagrant --version
Vagrant 1.5.4

# ERROR, with  response always about Provisioners::Base.
$ vagrant --help
Vagrant failed to initialize at a very early stage:
The plugins failed to load properly. The error message given is
shown below.
uninitialized constant Vagrant::Provisioners::Base
```

I looked at the code a bit and reread the documentation. 

I had run the Uninstall tool [1] prior to re-Installing, thinking that would be safer than manually deleting items as per the docs [2]

The problem was the Base Provisioners are apparently part of User data, and ~/.vagrant.d was not removed. Once I manually removed all 3 locations ,as per docs [2], all was good on the reinstall. 

So, may I submit a Pull request to add this file deletion? Or is there a reason it was not included?
Thank you!

1.[]vagrant-installers / package / support / darwin / uninstall.tool ; X.vagrant-installers/package/support/darwin/uninstall.tool at master · mitchellh/vagrant-installers
https://github.com/mitchellh/vagrant-installers/blob/master/package/support/darwin/uninstall.tool
```
# Collect the directories and files to remove
my_files=()
append my_files "/Applications/Vagrant"
append my_files "/usr/bin/vagrant"
```

2.[] ; X.Uninstalling Vagrant - Vagrant Documentation
http://docs.vagrantup.com/v2/installation/uninstallation.html
```
Removing the user data will remove all boxes, plugins, and any stored state that may be used by Vagrant. Removing the user data effectively makes Vagrant think it is once again a fresh install.
On every platform, remove the ~/.vagrant.d directory to delete the user data.
Running Vagrant will automatically regenerate any data necessary to run, so it is safe to remove the user data at any time.
```

**Comment by sethvargo** [comment]
Hi @AnneTheAgile 

We do not delete the user data because sometimes the Vagrant installation can get into a bad state, but users do not want to re-download all their boxes and plugins (which are stored in .vagrant.d). I think we would gladly accept a PR to output a message instructing the user to delete that directory if they are truly "done" with Vagrant, and explain the implications of doing so. Thanks!
