### ISSUE TITLE
"panic: runtime error: slice bounds out of range" when running vagrant

### ISSUE THREAD

**Issue by konrness** [mitchellh/vagrant-installers#41]
I previously had Vagrant 1.5.4 installed. I installed 1.6.3 over it and it caused this problem to happen. Then I uninstalled 1.6.3 and deleted the entire c:\HashiCorp directory and reinstalled 1.6.3 and still had this problem.

```
c:\HashiCorp\Vagrant\embedded\gems\gems>vagrant
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
runtime.panic(0x4a6540, 0x59180a)
        C:/Users/Mitchell/code/3rdparty/go/src/pkg/runtime/panic.c:266 +0xa6
main.main()
        c:/Users/Mitchell/code/mitchellh/vagrant-installers/substrate/launcher/m
ain.go:35 +0x19d3
```

This issue occurred because c:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.5.4 did not have a /lib/vagrant/pre-rubygems.rb file in it. It only has a tests directory.

Workaround: rename c:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.5.4 to a directory name that does not start with "vagrant-*", such as "vagrantx-1.5.4".

**Comment by sethvargo** [comment]
Hi there,

This has been fixed on master. Thanks!
