### ISSUE TITLE
Use mingw's bsdtar on windows xp

### ISSUE THREAD

**Issue by vweevers** [mitchellh/vagrant-installers#42]
As detailed in mitchellh/vagrant#3869 (and [specifically](https://github.com/mitchellh/vagrant/issues/3869#issuecomment-46767953)), gnuwin32's bsdtar doesn't work on Windows XP, while mingw's does. The simplest fix would be to add mingw to the PATH, but that might create other problems. But more importantly, I wonder why the binaries are bundled at all, when they're not used? Are they scheduled to be removed?

**Comment by sethvargo** [comment]
Hi there,

The next version of Vagrant will use the proper version. Thanks!

**Comment by vweevers** [comment]
:+1:

**Comment by vweevers** [comment]
@sethvargo According to [this comment](https://github.com/mitchellh/vagrant/issues/3869#issuecomment-129785401), the issue persists in 1.7.4. I can't confirm, so this is just a friendly FIY.
