### ISSUE TITLE
Windows Substrate & Packaging Issues

### ISSUE THREAD

**Issue by kadaan** [mitchellh/vagrant-installers#47]
The permissions on the rgloader folder are not setup correctly when the windows substrate is build.  The fix seems to be adding the following to loaders.pp
  } elsif $kernel == 'Windows' {
    $owner = "Administrators"
    $group = "Administrator"
    $mode  = "0644"

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previous update so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
