### ISSUE TITLE
OpenSSL certificate bundle can't be overridden

### ISSUE THREAD

**Issue by dcondomitti** [mitchellh/vagrant-installers#51]
I use a middleware that makes a TLS request to a remote host that uses a self-signed (well, signed by an  internal CA) certificate. It fails peer verification due to the active CA bundle being the one included with Vagrant. 

Normally I'd override SSL_CERT_FILE with the path to the root certificate but the vagrant boot script always overrides[0] that. I can change this to only set `SSL_CERT_FILE` if it's not already set but I'm not sure of its impact on other platforms.

```
$ bash -c 'SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem vagrant up'

< binding.pry in my Vagrantfile >

[4] (pry) main: 0> puts "SSL_CERT_FILE: %s" % OpenSSL::X509::DEFAULT_CERT_FILE
SSL_CERT_FILE: /vagrant-substrate/staging/embedded/ssl/cert.pem
...
[14] (pry) main: 0> http.use_ssl = true
[15] (pry) main: 0> http.get(uri.request_uri)
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /Applications/Vagrant/embedded/lib/ruby/2.0.0/net/http.rb:918:in `connect'
[16] (pry) main: 0> puts ENV['SSL_CERT_FILE']
/Applications/Vagrant/bin/../embedded/cacert.pem

```

[0] 
https://github.com/mitchellh/vagrant-installers/blob/master/substrate/modules/vagrant_installer/templates/vagrant.erb#L22-23

**Comment by drcraig** [comment]
I have the same problem. Our corporate policy requires us to use an internal mirror of RubyGems that uses an self-signed CA. I think it's just a simple matter of allowing the SSL_CERT_FILE variable to remain set if it's already so. Something like:

````bash
# Make ruby aware of our CA bundle if another is not already specified
if [ -z ${SSL_CERT_FILE+x} ]; then
  export SSL_CERT_FILE="${EMBEDDED_DIR}/cacert.pem"
fi
````

I don't seem to see this same problem on Linux. I'm guessing that the SSL_CERT_DIR variable is taking precedence there. On Macs, the certs are all inside the Keychain app, so I have to export them to file first.

**Comment by dcondomitti** [comment]
We ended up just using Casper to overwrite `Vagrant/embedded/cacert.pem` with a symlink to a certificate bundle exported from Keychain Access.

**Comment by drcraig** [comment]
Thanks @sethvargo! I take it this will show up in the next 1.7.5 release of Vagrant?

**Comment by sethvargo** [comment]
Yup!
