### ISSUE TITLE
Errors creating a substrate

### ISSUE THREAD

**Issue by jsteel44** [mitchellh/vagrant-installers#60]
I get errors while creating a substrate for Arch Linux. I managed to update it not long ago without much trouble, but now the ruby and bsdtar puppet modules are failing:

https://bpaste.net/show/98e1fc667f3a
https://bpaste.net/show/2d07989b12c9

I think notable errors (from the above pastes) are:
.ext/include/i686-linux/ruby/config.h:81:25: error: expected ')' before 'PRI_LL_PREFIX'
symbol lookup error: embedded/lib/libreadline.so.6: undefined symbol: UP

Let me know if you need any further information from me. Thanks

**Comment by jsteel44** [comment]
This patch fixes the bsdtar module issue:
http://pastie.org/10419063

I'm still having the same issue with the ruby module. Thanks

**Comment by jsteel44** [comment]
Commenting out "environment      => $autotools_environment," from substrate/modules/ruby/manifests/source.pp fixes the issue, but I'm not sure what implication that has on the resulting package. Can you advise?

**Comment by jsteel44** [comment]
Appending -O2 to CFLAGS in modules/vagrant_substrate/manifests/staging/posix.pp seems to be another solution for me.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple updates since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by jsteel44** [comment]
@chrisroberts yes please re-open; this isn't resolved with the latest version. Taking a while to look into an issue is no problem, so don't be sorry about that. I even said I had a workaround. But closing it with no resolution does not make sense to me. Is a silent/hidden problem better than a reported problem in your eyes?

**Comment by jsteel44** [comment]
Sorry I didn't mean that to sound aggressive. I was just confused why you didn't ask if I was still having the issue first. I've been updating this case as I've found more information about it so for the first reply to be "closed" is unexpected.

**Comment by chrisroberts** [comment]
@jsteel44 Hey. #107 updated multiple things including bumping versions of included libraries. It has been merged to master, so can you confirm you are still having issues, and if so I'll reopen the issue. Thanks!

**Comment by jsteel44** [comment]
@chrisroberts just tried the latest in git and am still seeing the same error: https://bpaste.net/show/3009be9506cf

**Comment by jsteel44** [comment]
@chrisroberts can you reopen this as you proposed? Thanks
