### ISSUE TITLE
Vagrant DMG installer fails silently on clean 10.10.4

### ISSUE THREAD

**Issue by nacht** [mitchellh/vagrant-installers#61]
#Vagrant DMG installer fails silently on a brand new MBP running 10.10.4.#

**To Reproduce**
* Download latest OSX DMG from vagrantup.com
* Double-click PKG

**Expected Behavior** 
* Expects Vagrant to install cleanly
* Or Expects Vagrant to fail loudly
 
**Observed Behaviour**
* Vagrant shows sucessful install screen
* vagrant CLI does not run
* no /usr/local/bin tree created

**Notes**
Commit 22a3f46@mitchellh move to /usr/local [GH-54] break this as on a default 10.10.4 install there is no /usr/local/bin only /usr/bin.

**Comment by enkeboll** [comment]
Just a heads up, I had this issue today on a new 10.10.5.  Creating `/usr/local/bin` fixed the issue
