### ISSUE TITLE
updated openssl version

### ISSUE THREAD

**Issue by SimonPe** [mitchellh/vagrant-installers#76]
current is  openssl-1.0.2f

**Comment by sethvargo** [comment]
Hi @SimonPe 

Thank you for opening an issue. We always update to the latest openssl when we publish a new build. Additionally, Vagrant is not designed for real production scenarios, so the attack vector is relatively small.

**Comment by SimonPe** [comment]
@sethvargo The main problem is that the openssl people don't keep their old versions around, which breaks rebuilding the substrate.
This in turn breaks distribution package rebuilds (in this case I was trying to rebuild the archlinux package)

**Comment by sethvargo** [comment]
Hi @SimonPe 

Ah yes. This is correct. We cache them internally for that reason, but I understand how that can be frustrating if you just want to build your own installers. If you want to bump the ossl versions in a PR, I'll merge it :smile:

**Comment by mawatech** [comment]
created pull request #80

**Comment by chrisroberts** [comment]
Resolved by #107
