### ISSUE TITLE
Missing icon and website on Windows

### ISSUE THREAD

**Issue by sethvargo** [mitchellh/vagrant-installers#77]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

-> 1.8.1
 
### Host operating system
This is the operating system that you run locally.

-> Windows

### Expected behavior
What should have happened?

-> There should be an icon and link to the website

### Actual behavior
What actually happened?

-> There is nothing

### Steps to reproduce
1. Install
2. Vagrant
3. On Windows

![explorer_2016-03-07_03-27-16](https://cloud.githubusercontent.com/assets/75278/13559443/8f15a314-e414-11e5-828f-6e2d7bcb40a8.png)

**Comment by sethvargo** [comment]
Refs https://github.com/mitchellh/vagrant/issues/7111

**Comment by sethvargo** [comment]
Hey @chrisroberts - do you see this on your Windows machine too? Any ideas?

**Comment by chrisroberts** [comment]
@sethvargo see #86. There's a mention of providing a URL. Where is that expected to be displayed?

**Comment by sethvargo** [comment]
@chrisroberts that should be the actual Vagrant icon (just like on mac)

**Comment by chrisroberts** [comment]
Resolved via #86
