### ISSUE TITLE
Please add the entry point script (aka 'how to build') to the README

### ISSUE THREAD

**Issue by themasterchef** [mitchellh/vagrant-installers#85]
Hi

I'm contemplating building vagrant-installers on OS X, including substrate, but it's not clear where the actual entry point script is. There's some shell scripts, some Puppet manifests, some Terraform, and some shell scripts that might depend on other scripts... you get what I mean.

Please could you add a little example to the README indicating where the entry point is and how to call it to kick the whole build process off?

**Comment by jsteel44** [comment]
This is Arch's build script if it helps https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/vagrant-substrate

The build function might be all you need.

**Comment by chrisroberts** [comment]
Fixed via #107
